import {describe,it,expect,beforeEach} from 'vitest';
import {settingsRoutes} from '../workspace/production-settings.js';
import {initialDefinition} from '../workspace/production-forms.js';
import {shiftRoutes,allocationSources,shiftWorkDate} from '../workspace/production-shifts.js';
import type {WorkspaceTx} from '../workspace/store.js';
import type {User} from '../workspace/model.js';
// Clone-on-read models transaction isolation: rejected actions never mutate persisted state.
class MemoryTx { rows=new Map<string,any>(); async get(k:string,id:string){return structuredClone(this.rows.get(k+':'+id));} async put(k:string,id:string,v:any){this.rows.set(k+':'+id,structuredClone(v));} async list(k:string){return [...this.rows].filter(([key])=>key.startsWith(k+':')).map(([,v])=>structuredClone(v));}}
const user=(id:string,role:string,forms=['arr'])=>({id,username:id,role,forms,active:true} as User);
const manager=user('manager','manager'),lead=user('lead','reviewer'),otherLead=user('other','reviewer'),owner=user('owner','owner'),admin=user('admin','admin');
const op={id:'person-1',username:'person-1'},other={id:'person-2',username:'person-2'};
const at=(h:number)=>`2026-10-01T${String(h).padStart(2,'0')}:00:00Z`;
const assigned={stage:'Cleaning / Decontamination',station:'W1',product:'Sleeves',productId:'sleeves'};
describe('continuous production shifts',()=>{
 let tx:MemoryTx;
 const call=(route:string,input:any={},u:User|undefined=undefined,o:any=op)=>shiftRoutes(tx as unknown as WorkspaceTx,u,o,route,input);
 const start=(extra:any={})=>call('production-shift-start',{workDate:'2026-10-01',shift:'day',team:'Team A',actualTime:at(8),assignment:assigned,...extra,data:{sopClarity:10,...extra.data}}).then(r=>r.shift);
 const action=async(r:any,a:string,extra:any={},u?:User,o:any=op)=>call('production-shift-action',{id:r.id,revision:r.revision,action:a,...(a==='end'?{confirmed:true}:{}),...extra},u,o);
 beforeEach(async()=>{tx=new MemoryTx();await tx.put('production-settings','main',{crewAssignments:{'person-1':{team:'Team A',leadId:'lead',managerId:'manager'}}});for(const u of [lead,otherLead])await tx.put('user',u.id,u);await tx.put('production-product','sleeves',{id:'sleeves',name:'Sleeves',active:true,aliases:[]});await tx.put('production-form','arr',{identity:'production-demo-arr',version:'0.1.0',definition:initialDefinition('arr')});});
 it('preserves and validates default shift through crew settings saves',async()=>{
  await tx.put('production-operator','person-1',{...op,active:true});
  const input={revision:1,settings:{teams:['Team A','Team C'],cutoffHour:3,crewAssignments:{'person-1':{team:'Team C',defaultShift:'swing'}}}};
  const result=await settingsRoutes(tx as any,owner,'production-settings-save',input);
  expect(result).toBeDefined();
  if(!result)throw new Error('Expected production-settings-save result.');
  expect(result.settings.crewAssignments['person-1'].defaultShift).toBe('swing');
  input.revision=result.settings.revision;input.settings.crewAssignments['person-1'].defaultShift='invalid';await expect(settingsRoutes(tx as any,owner,'production-settings-save',input)).rejects.toThrow('Day or Swing');
 });
 it('defaults new shifts from configured crew but preserves a chosen shift override',async()=>{
  await tx.put('production-settings','main',{crewAssignments:{'person-1':{team:'Team C',defaultShift:'swing'}}});
  let s=await start({shift:undefined});expect(s.team).toBe('Team C');expect(s.shift).toBe('swing');s=(await action(s,'end',{actualTime:at(9)})).shift;
  const next=await start({workDate:'2026-10-02',actualTime:'2026-10-02T08:00:00Z',shift:'day'});expect(next.shift).toBe('day');expect((await call('production-shift-detail',{id:s.id})).shift.shift).toBe('swing');
 });
 it.each(['associate','demo_preselected'])('accepts %s readiness without inventing an SOP score',async(source)=>{
  const s=await start({sopReady:true,sopReadySource:source,data:{sopClarity:undefined}});
  expect(s.segments[0]).toMatchObject({kind:'production',sopReadySource:source});expect(s.data.sopClarity).toBeUndefined();expect(s.history[0].after.segments[0].sopReadySource).toBe(source);
 });
 it('accepts help without a score and still blocks production until approval',async()=>{
  const s=await start({needsReadiness:true,sopReady:false,data:{sopClarity:undefined}});expect(s.segments[0].kind).toBe('training');expect(s.data.sopClarity).toBeUndefined();await expect(action(s,'begin-work',{actualTime:at(9)})).rejects.toThrow('confirmation');
 });
 it('rejects false or string readiness without a score',async()=>{
  for(const sopReady of [false,'true',null])await expect(start({sopReady,data:{sopClarity:undefined}})).rejects.toThrow('Select your SOP');expect(await tx.list('production-shift')).toHaveLength(0);
 });
 it('allows waiting to production with explicit readiness and no score',async()=>{
  let s=await start({waitingForAssignment:true,data:{sopClarity:undefined}});s=(await action(s,'changeover',{actualTime:at(9),assignment:assigned,sopReady:true,sopReadySource:'associate',data:{}})).shift;expect(s.segments[1]).toMatchObject({kind:'production',sopReadySource:'associate'});expect(s.data.sopClarity).toBeUndefined();
 });
 it('preserves optional feedback typed at changeover without requiring end-phase answers or clearing earlier notes',async()=>{
  let s=await start({data:{note:'Keep earlier note'}});
  s=(await action(s,'changeover',{actualTime:at(10),assignment:{...assigned,stage:'Packaging'},data:{quality:8,experience:7,workedWell:'Shared feedback'}})).shift;
  expect(s.data).toMatchObject({note:'Keep earlier note',quality:8,experience:7,workedWell:'Shared feedback'});
  await expect(action(s,'end',{actualTime:at(12),data:{quality:99}})).rejects.toThrow('Invalid');
  s=(await action(s,'end',{actualTime:at(12),data:{}})).shift;expect(s.data.note).toBe('Keep earlier note');expect(s.data.quality).toBe(8);
 });
 it('preserves actual and recorded timestamps, exact form snapshot, and one shift per work date',async()=>{const s=await start();expect(s.createdAt).not.toBe(at(8));expect(s.segments[0].start).toBe('2026-10-01T08:00:00.000Z');await tx.put('production-form','arr',{version:'0.1.1'});expect((await call('production-shift-detail',{id:s.id})).shift.formSnapshot.definition.fields[0].key).toBe('workDate');await expect(start()).rejects.toThrow('already exists');await expect(start({workDate:'2026-10-02'})).rejects.toThrow('existing open');});
 it('atomically moves boundaries and rejects overlaps, gaps, stale revisions, negative counts',async()=>{let s=await start();s=(await action(s,'changeover',{actualTime:at(10),assignment:{...assigned,stage:'Packaging'},reportedMoves:0})).shift;expect(s.segments[0].end).toBe(s.segments[1].start);expect(s.segments[0].reportedMoves).toBe(0);const bad=structuredClone(s.segments);bad[1].start=at(9);await expect(action(s,'correct',{segments:bad,reason:'fix'})).rejects.toThrow('shared boundary');expect((await call('production-shift-detail',{id:s.id})).shift.revision).toBe(s.revision);const good=structuredClone(s.segments);good[0].end=at(9);good[1].start=at(9);const next=(await action(s,'correct',{segments:good,reason:'Actual changeover'})).shift;expect(next.history.at(-1).before.segments[0].end).not.toBe(next.segments[0].end);await expect(action(s,'end',{actualTime:at(11)})).rejects.toThrow('changed');await expect(action(next,'end',{actualTime:at(11),reportedMoves:-1})).rejects.toThrow('nonnegative');});
 it('readiness is a narrow automatic exception; production blocked until associate then lead confirms',async()=>{let s=await start({needsReadiness:true,data:{recognition:'Private appreciation'}});const list=await call('production-shift-list',{from:'2026-10-01',to:'2026-10-01'},lead);expect(list.shifts).toHaveLength(0);expect(list.readiness).toHaveLength(1);expect(JSON.stringify(list)).not.toContain('Private appreciation');await expect(call('production-shift-detail',{id:s.id},otherLead)).rejects.toThrow('unavailable');await expect(action(s,'begin-work',{actualTime:at(9)})).rejects.toThrow('confirmation');await expect(action(s,'changeover',{actualTime:at(9),assignment:assigned})).rejects.toThrow('readiness');await expect(action(s,'readiness-confirm',{},lead)).rejects.toThrow('Associate');s=(await action(s,'readiness-ready')).shift;const confirmed=await action(s,'readiness-confirm',{},lead);expect(confirmed.shift).toBeUndefined();s=(await call('production-shift-detail',{id:s.id})).shift;s=(await action(s,'begin-work',{actualTime:at(9)})).shift;s=(await action(s,'end',{actualTime:at(12),reportedMoves:100})).shift;const sources=await allocationSources(tx as any,'2026-10-01','sleeves','Cleaning / Decontamination');expect(sources).toHaveLength(1);expect(sources[0].minutes).toBe(180);expect(s.segments[0].kind).toBe('training');});
 it('shared correction defaults on, revocable, read-only share cannot mutate; recognition filtered from audit',async()=>{let s=await start({data:{recognition:'Keep private',recognitionPeople:['person-2']}});await expect(call('production-shift-detail',{id:s.id},lead)).rejects.toThrow();s=(await action(s,'share',{leadId:'lead'},manager)).shift;const view=(await call('production-shift-detail',{id:s.id},lead)).shift;expect(view.canCorrect).toBe(true);expect(JSON.stringify(view)).not.toContain('Keep private');await expect(action(s,'end',{actualTime:at(12)},lead)).rejects.toThrow('reason');s=(await action(s,'share',{leadId:'lead',allowCorrections:false},manager)).shift;await expect(action(s,'end',{actualTime:at(12),reason:'Absent'},lead)).rejects.toThrow('permission');s=(await action(s,'retract',{leadId:'lead'},manager)).shift;await expect(call('production-shift-detail',{id:s.id},lead)).rejects.toThrow();});
 it('Owner visibility alone is not operational; manager can cross crew; completed shift requires reopen',async()=>{let s=await start();expect((await call('production-shift-detail',{id:s.id},owner)).shift.canManage).toBe(false);await expect(action(s,'end',{actualTime:at(12),reason:'Assist'},owner)).rejects.toThrow('permission');await expect(action(s,'end',{actualTime:at(12),reason:'Assist'},admin)).rejects.toThrow('permission');await expect(action(s,'close',{},manager)).rejects.toThrow('complete');await tx.put('production-permission','owner',{operationalManager:true});s=(await action(s,'end',{actualTime:at(12),reason:'On behalf'},owner)).shift;s=(await action(s,'close',{},manager)).shift;await expect(action(s,'correct',{segments:s.segments,reason:'Fix'},manager)).rejects.toThrow('Reopen');s=(await action(s,'reopen',{reason:'Check times'},manager)).shift;expect(s.status).toBe('needs_attention');expect(s.history.at(-1).role).toBe('manager');await expect(call('production-shift-detail',{id:s.id},undefined,other)).rejects.toThrow();});
 it('bulk close validates the entire selection before writing any shifts',async()=>{let s=await start();s=(await action(s,'end',{actualTime:at(12)})).shift;await expect(call('production-shift-close-many',{shifts:[{id:s.id,revision:s.revision},{id:'missing',revision:1}]},manager)).rejects.toThrow('changed');expect((await call('production-shift-detail',{id:s.id})).shift.status).toBe('submitted');const result=await call('production-shift-close-many',{shifts:[{id:s.id,revision:s.revision}]},manager);expect(result.shifts[0].status).toBe('closed');});
 it('ending during preparation does not leave a false readiness waiting queue',async()=>{let s=await start({needsReadiness:true});s=(await action(s,'end',{actualTime:at(9)})).shift;expect(s.readiness.status).toBe('cancelled');expect((await call('production-shift-list',{from:'2026-10-01',to:'2026-10-01'},lead)).readiness).toHaveLength(0);expect(await allocationSources(tx as any,'2026-10-01','Sleeves','Cleaning / Decontamination')).toEqual([]);});
 it('reopened submitted shifts can be corrected and resubmitted without inventing another open segment',async()=>{let s=await start();s=(await action(s,'end',{actualTime:at(12)})).shift;s=(await action(s,'reopen',{reason:'Actual end was earlier'},manager)).shift;const segments=structuredClone(s.segments);segments[0].end=at(11);s=(await action(s,'correct',{segments,reason:'Corrected against operator report'},manager)).shift;s=(await action(s,'submit',{},manager)).shift;expect(s.status).toBe('submitted');expect(s.segments).toHaveLength(1);expect((await allocationSources(tx as any,'2026-10-01','Sleeves','Cleaning / Decontamination'))[0].minutes).toBe(180);});
 it('uses pinned required questions when the live form changes and audits answer corrections',async()=>{const definition=initialDefinition('arr');definition.fields.push({key:'wrapup',label:'Wrap up',type:'text',phase:'eod',required:true,active:true,page:1,options:[]});await tx.put('production-form','arr',{version:'0.1.0',definition});let s=await start();await tx.put('production-form','arr',{version:'0.1.1',definition:initialDefinition('arr')});await expect(action(s,'end',{actualTime:at(12)})).rejects.toThrow('Wrap up');s=(await action(s,'end',{actualTime:at(12),data:{wrapup:'Complete'}})).shift;s=(await action(s,'reopen',{reason:'Edit text'},manager)).shift;s=(await action(s,'correct',{segments:s.segments,data:{wrapup:'Corrected'},reason:'Clarification'},manager)).shift;expect(s.history.at(-1).before.data.wrapup).toBe('Complete');expect(s.history.at(-1).after.data.wrapup).toBe('Corrected');});
 it('unmatched products are not trusted as caller-supplied catalog ids; later alias mapping is reflected in allocation sources',async()=>{let s=await start({assignment:{...assigned,product:'Sleevs',productId:'malicious-existing-id'}});expect(s.segments[0].productId).not.toBe('malicious-existing-id');s=(await action(s,'end',{actualTime:at(9)})).shift;await tx.put('production-product','sleeves',{id:'sleeves',name:'Sleeves',active:true,aliases:['Sleevs']});expect((await allocationSources(tx as any,'2026-10-01','Sleeves','Cleaning / Decontamination'))[0].minutes).toBe(60);});

 it('hides restricted recognition changes and unpublished form drafts from shared leads and ungranted Admins',async()=>{const form=await tx.get('production-form','arr');form.draft={definition:{secret:'Unpublished sensitive draft'}};form.versions=[{notes:'Old internal wording'}];await tx.put('production-form','arr',form);let s=await start({data:{recognition:'Initial private'}});expect(JSON.stringify(s.formSnapshot)).not.toContain('Unpublished');s=(await action(s,'share',{leadId:'lead'},manager)).shift;s=(await action(s,'correct',{segments:s.segments,data:{recognition:'Private changed'},reason:'Private changed'},manager)).shift;for(const u of [lead,admin]){const result=await call('production-shift-detail',{id:s.id},u);expect(JSON.stringify(result)).not.toContain('Initial private');expect(JSON.stringify(result)).not.toContain('Private changed');expect(JSON.stringify(result)).not.toContain('Unpublished');}expect(JSON.stringify((await call('production-shift-detail',{id:s.id},owner)))).toContain('Private changed');});
 it('records optional segment counts and downtime without treating missing as zero or double subtracting training',async()=>{let s=await start({needsReadiness:true});s=(await action(s,'readiness-ready')).shift;await action(s,'readiness-confirm',{},lead);s=(await call('production-shift-detail',{id:s.id})).shift;s=(await action(s,'begin-work',{actualTime:at(9)})).shift;s=(await action(s,'end',{actualTime:at(12),reportedMoves:0,extras:{countType:'exact',rejected:2,rework:3,lot:'Fictional lot',exception:'Short stoppage',interruptionMinutes:30}})).shift;const rows=await allocationSources(tx as any,'2026-10-01','Sleeves','Cleaning / Decontamination');expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({grossMinutes:180,downtimeMinutes:30,minutes:150,reportedMoves:0});expect(s.segments[1].extras.lot).toBe('Fictional lot');});
 it('validates future dates, explicit SOP choice, and workdate corrections; reopened associates can correct their own shift',async()=>{await expect(start({workDate:'2099-01-01'})).rejects.toThrow('future');await expect(start({data:{sopClarity:undefined}})).rejects.toThrow('Select your SOP');let s=await start();s=(await action(s,'end',{actualTime:at(12)})).shift;await expect(action(s,'correct',{segments:s.segments,reason:'Not reopened'})).rejects.toThrow('permission');s=(await action(s,'reopen',{reason:'Please fix'},manager)).shift;expect((await call('production-shift-detail',{id:s.id})).shift.canCorrect).toBe(true);s=(await action(s,'correct',{segments:s.segments,workDate:'2026-09-30',reason:'Wrong date'})).shift;expect(s.workDate).toBe('2026-09-30');s=(await action(s,'submit')).shift;expect(s.status).toBe('submitted');});

 it('keeps original workdate across midnight and defaults before the configured Pacific cutoff',async()=>{expect(shiftWorkDate('2026-10-02T07:30:00Z',3)).toBe('2026-10-01');expect(shiftWorkDate('2026-10-02T10:00:00Z',3)).toBe('2026-10-02');expect(shiftWorkDate('2026-10-02T10:00:00Z',4)).toBe('2026-10-01');let s=await start({workDate:undefined,shift:'swing',actualTime:'2026-10-02T07:30:00Z'});expect(s.workDate).toBe('2026-10-01');s=(await action(s,'end',{actualTime:'2026-10-02T09:00:00Z'})).shift;expect(s.workDate).toBe('2026-10-01');expect((await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination'))[0].minutes).toBe(90);});
 it('requires explicit end confirmation and rejects interruption longer than elapsed production',async()=>{let s=await start();await expect(action(s,'end',{actualTime:at(9),confirmed:false})).rejects.toThrow('confirm End Shift');await expect(action(s,'end',{actualTime:at(9),extras:{interruptionMinutes:61}})).rejects.toThrow('exceed');expect((await call('production-shift-detail',{id:s.id})).shift.segments[0].end).toBeNull();s=(await action(s,'end',{actualTime:at(9),extras:{interruptionMinutes:60}})).shift;expect((await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination'))[0].minutes).toBe(0);});
 it('cannot convert pending SOP training to production through a correction payload or forged false flag',async()=>{let s=await start({needsReadiness:true});const changed=structuredClone(s.segments);changed[0].kind='production';s=(await action(s,'correct',{segments:changed,needsReadiness:false,reason:'Attempted kind edit'})).shift;expect(s.segments[0].kind).toBe('training');await expect(action(s,'changeover',{actualTime:at(9),assignment:assigned,needsReadiness:false})).rejects.toThrow('readiness');await expect(action(s,'begin-work',{actualTime:at(9),needsReadiness:false})).rejects.toThrow('confirmation');});

 it('rejects impossible actual dates and beyond-tolerance future clock edits',async()=>{await expect(start({actualTime:'2026-02-30T08:00:00Z'})).rejects.toThrow('valid work date');await expect(start({actualTime:new Date(Date.now()+600000).toISOString()})).rejects.toThrow('future');});
 it('preserves not-counted versus an explicit zero and rejects contradictory count descriptors',async()=>{let s=await start();await expect(action(s,'end',{actualTime:at(9),reportedMoves:0,extras:{countType:'not_counted'}})).rejects.toThrow('Leave moves blank');await expect(action(s,'end',{actualTime:at(9),extras:{countType:'exact'}})).rejects.toThrow('Enter moves');s=(await action(s,'changeover',{actualTime:at(9),assignment:assigned,extras:{countType:'not_counted'}})).shift;s=(await action(s,'end',{actualTime:at(10),reportedMoves:0,extras:{countType:'exact'}})).shift;const rows=await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination');expect(rows.map(r=>r.reportedMoves)).toEqual([null,0]);});

 it('validates corrections against historical questions across phases and permits clearing optional answers',async()=>{let s=await start({data:{mood:7,note:'Temporary note'}});s=(await action(s,'correct',{segments:s.segments,data:{mood:8,note:''},reason:'Correct initial response'})).shift;expect(s.data.mood).toBe(8);expect(s.data.note).toBeUndefined();await expect(action(s,'correct',{segments:s.segments,data:{mood:99},reason:'Invalid scale'})).rejects.toThrow('Invalid');s=(await action(s,'share',{leadId:'lead'},manager)).shift;await expect(action(s,'correct',{segments:s.segments,data:{recognition:'Injected'},reason:'Try'},lead)).rejects.toThrow('restricted');});

 it('accepts the full long-catalog product name without truncation or trusting an arbitrary id',async()=>{const name='Fictional specialized device model '.repeat(14);await tx.put('production-product','long-candidate',{id:'long-candidate',name,active:true,aliases:[]});const s=await start({assignment:{...assigned,product:name}});expect(s.segments[0].product).toBe(name);expect(s.segments[0].originalProduct).toBe(name.trim());expect(s.segments[0].productId).toBe('long-candidate');});

 it('preserves UI interruptionMinutes and enforces configured crews rather than arbitrary request values',async()=>{await tx.put('production-settings','main',{teams:['Configured Crew'],crewAssignments:{}});await expect(start({team:'Invented Crew'})).rejects.toThrow('configured crew');let s=await start({team:'Configured Crew'});s=(await action(s,'end',{actualTime:at(9),data:{interruptionMinutes:20}})).shift;expect(s.segments[0].extras.interruptionMinutes).toBe(20);expect((await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination'))[0].minutes).toBe(40);});

 it('read/comment-only lead can add consultation notes but cannot change source answers or review unshared shifts',async()=>{let s=await start();await expect(action(s,'comment',{note:'Not shared'},lead)).rejects.toThrow('unavailable');s=(await action(s,'share',{leadId:'lead',allowCorrections:false},manager)).shift;const view=(await call('production-shift-detail',{id:s.id},lead)).shift;expect(view.canComment).toBe(true);expect(view.canCorrect).toBe(false);s=(await action(s,'comment',{note:'Internal consultation only'},lead)).shift;expect(s.status).toBe('in_progress');expect(s.data.note).toBeUndefined();expect(s.history.at(-1).reason).toBe('Internal consultation only');s=(await action(s,'reviewed',{},lead)).shift;expect(s.history.at(-1).action).toBe('reviewed');await expect(action(s,'comment',{note:'Owner without operational role'},owner)).rejects.toThrow('supervisor');});

 it('records repeated waiting periods without catalog entries, production minutes, or readiness queues',async()=>{
  let s=await start({waitingForAssignment:true,assignment:null,data:{sopClarity:undefined,note:'Await dispatch'}});
  expect(s.segments[0]).toMatchObject({kind:'waiting',product:'',stage:'Waiting for assignment',reportedMoves:null});expect(s.readiness).toBeNull();
  expect(await tx.list('production-unmatched')).toEqual([]);
  await expect(action(s,'changeover',{actualTime:at(9),assignment:assigned})).rejects.toThrow('SOP understanding');
  s=(await action(s,'changeover',{actualTime:at(9),assignment:assigned,data:{sopClarity:10}})).shift;
  s=(await action(s,'changeover',{actualTime:at(10),waitingForAssignment:true,reportedMoves:50})).shift;
  s=(await action(s,'changeover',{actualTime:at(11),assignment:assigned,needsReadiness:true})).shift;
  expect(s.segments.map((v:any)=>v.kind)).toEqual(['waiting','production','waiting','training']);
  s=(await action(s,'readiness-ready')).shift;await action(s,'readiness-confirm',{},lead);s=(await call('production-shift-detail',{id:s.id})).shift;
  s=(await action(s,'begin-work',{actualTime:at(12)})).shift;s=(await action(s,'end',{actualTime:at(13)})).shift;
  const rows=await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination');expect(rows.map(v=>v.minutes)).toEqual([60,60]);expect(rows[0].reportedMoves).toBe(50);expect(s.data.note).toBe('Await dispatch');
  const correction=structuredClone(s.segments);correction[0].kind='production';correction[0].product='Sleeves';
  s=(await action(s,'reopen',{reason:'Review'},manager)).shift;s=(await action(s,'correct',{segments:correction,reason:'Preserve waiting kind'},manager)).shift;expect(s.segments[0].kind).toBe('waiting');expect(s.segments[0].product).toBe('');
 });
 it('can end while still waiting and abandon preparation for waiting without granting production readiness',async()=>{
  let s=await start({needsReadiness:true});s=(await action(s,'changeover',{actualTime:at(9),waitingForAssignment:true,needsReadiness:true})).shift;expect(s.readiness).toBeNull();
  s=(await action(s,'end',{actualTime:at(10),reportedMoves:999,extras:{rejected:99},data:{recognition:'End reflection'}})).shift;
  expect(s.status).toBe('submitted');expect(s.segments[1].reportedMoves).toBeNull();expect(s.segments[1].extras).toBeUndefined();expect(s.data.recognition).toBe('End reflection');expect(await allocationSources(tx as any,s.workDate,'Sleeves','Cleaning / Decontamination')).toEqual([]);
  expect((await call('production-shift-list',{from:s.workDate,to:s.workDate},lead)).readiness).toEqual([]);
 });

});
