# Generated by Django 4.2.1 on 2023-06-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_productservicetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='productp_service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.productservicetype'),
        ),
    ]
