# Generated by Django 4.2.1 on 2023-06-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_revenuetype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='productp_service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.productservicetype'),
        ),
    ]
