# Generated by Django 4.2.1 on 2023-06-29 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_productservice_productp_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetype',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 7, 57, 56, 785684)),
        ),
    ]
