# Generated by Django 4.2.1 on 2023-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_revenuetype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
