# Generated by Django 4.2.1 on 2023-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_revenuetype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservicetype',
            name='productp_service_type',
            field=models.CharField(max_length=200),
        ),
    ]
