# Generated by Django 4.2.1 on 2023-10-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role'),
        ('services', '0008_alter_productservicetype_productp_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptedMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_months', to='authentication.company')),
            ],
        ),
    ]
