# Generated by Django 4.2.1 on 2023-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role'),
        ('services', '0009_exceptedmonths'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExceptedMonths',
            new_name='ExpectedMonths',
        ),
    ]
