# Generated by Django 4.2.1 on 2024-03-14 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_role'),
        ('services', '0010_rename_exceptedmonths_expectedmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_product_service', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='productservicetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_product_service_type', to='authentication.company'),
        ),
    ]
