# Generated by Django 4.2.7 on 2024-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_productservice_company_productservicetype_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('memo_description', models.TextField(blank=True, null=True)),
                ('account_class', models.CharField(max_length=255)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.productservice')),
            ],
        ),
    ]
