# Generated by Django 4.2.7 on 2024-08-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_exceltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productservice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productservicetype',
            name='company',
        ),
        migrations.DeleteModel(
            name='ExcelTransaction',
        ),
    ]
