# Generated by Django 4.2.1 on 2023-06-19 07:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, size=None)),
                ('deffered_revenue', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, size=None)),
                ('billing', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, size=None)),
                ('arr', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(null=True)),
                ('customer_name', models.CharField(max_length=400)),
                ('transaction_name', models.CharField(max_length=100)),
                ('order_close_data', models.DateField()),
                ('billing_method', models.CharField(max_length=30)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.IntegerField(blank=None, default=None)),
                ('invoice_adresss', models.TextField(max_length=300, null=True)),
                ('other_invoice_info', models.TextField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('s_start_d', models.DateTimeField(blank=True, null=True)),
                ('s_end_d', models.DateTimeField(blank=True, null=True)),
                ('subscription_status', models.CharField(blank=True, choices=[('active', 'active'), ('pending renewal', 'pending renewal'), ('cancelled', 'cancelled')], max_length=200, null=True)),
                ('subscription_terms_month', models.IntegerField(default=None, null=True)),
                ('arr', models.IntegerField(default=None, null=True)),
                ('sale_price', models.IntegerField(default=0)),
                ('total_revenue', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='invoice.calculation')),
                ('productp_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.productservice')),
                ('tansaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tansaction', to='invoice.transaction')),
            ],
        ),
    ]
