# Generated by Django 4.2.1 on 2023-06-19 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_item_calculation_calculation_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
