# Generated by Django 4.2.1 on 2023-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_calculationmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='f_cst_name',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
