# Generated by Django 4.2.1 on 2023-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_transaction_f_cst_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedate',
            name='close_period',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='f_cst_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
