# Generated by Django 4.2.1 on 2023-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_closedate_close_period_alter_transaction_f_cst_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedate',
            name='close_period',
            field=models.BooleanField(default=True),
        ),
    ]
