# Generated by Django 4.2.1 on 2023-07-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_closedate_close_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
