# Generated by Django 4.2.1 on 2023-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_item_cancel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrGracePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(default=0)),
            ],
        ),
    ]
