# Generated by Django 4.2.1 on 2023-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_transaction_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='red_flag',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
