# Generated by Django 4.2.1 on 2023-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_item_red_flag_transaction_red_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='arr',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_revenue',
            field=models.FloatField(),
        ),
    ]
