# Generated by Django 4.2.1 on 2023-10-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role'),
        ('invoice', '0016_alter_item_amount_alter_item_arr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrgraceperiod',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_grace_period', to='authentication.company'),
        ),
    ]
