# Generated by Django 4.2.1 on 2023-10-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_role'),
        ('invoice', '0017_arrgraceperiod_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrgraceperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_grace_period', to='authentication.company'),
        ),
    ]
