# Generated by Django 4.2.7 on 2024-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_transaction_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_number',
            field=models.TextField(blank=None, default=None),
        ),
    ]
