# Generated by Django 4.2.7 on 2024-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_transaction_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_number',
            field=models.IntegerField(blank=None, default=None),
        ),
    ]
