# Generated by Django 4.2.7 on 2024-08-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_transaction_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
    ]
