# Generated by Django 4.2.1 on 2023-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='realm_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
