# Generated by Django 4.2.1 on 2024-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
