# Generated by Django 4.2.1 on 2024-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_is_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User with staff input'), (3, 'User with view only'), (4, 'SUPERADMIN')], null=True),
        ),
    ]
